Homework 7
AlexSmi/python-course-alphabet pull request #6
Opened 2019-05-28 12:12 UTC by AlexSmi

2019-05-28 17:03 UTC, yuriimchg requested changes
перевірив, все ок, крім дат
лінтер не свариться :+1: 
також мені сподобалася клацалка в навігації

ще, з точки зору користувача, зручніше було б, якби фільми на сторінці фільмів були в 2 рядки або хоча б одним рядком посередині (але це не вимагається в завданні, відповідно не вимагається мною - просто як хороша практика)

2019-05-28 17:03 UTC, yuriimchg commented on template_language/homework/run.py
> +default_year = 2010
краще `initial_year` чи щось таке

2019-05-28 17:03 UTC, yuriimchg commented on template_language/homework/templates/movies.html
> +          {% if item.get('year') | int > default_year %}
*`...and left only movies not older than 2010 year by filtering them with the if statement...`*

мають бути з 2010 включно (в тебе стартують з 2011)

2019-05-29 15:18 UTC, ekut2104 approved these changes

2019-05-30 07:56 UTC, yuriimchg approved these changes

2019-05-30 07:57 UTC, merged